"""empty message

Revision ID: b4a20828d5b0
Revises: 
Create Date: 2024-02-28 15:59:07.819249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4a20828d5b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('account_google')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_google',
    sa.Column('id', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encrypted_password', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_pkey')
    )
    # ### end Alembic commands ###
